---
title: "Dataset validatie overstromingen - Dijle"
author: "Dries Adriaens"
date: "26-10-2020"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(watina)
library(ggplot2)
library(lubridate)
library(dplyr)
library(stringr)
library(tidyr)
library(sf)
library(leaflet)
```

```{r connection}
watina <- connect_watina()
```

# Komgrond Neerijse

We vragen al de meetpunten met peilbuis (piëzometer) op die gelegen zijn in de komgrond van Neerijse in de vallei van de Dijle. Dat gebeurt met behulp van het R-package `Watina`.

```{r meetpunten}
locaties <- get_locs(watina,
                     loc_vec = c("DYLP137", "DYLP105", "DYLP088", "DYLB028", "DYLB005", "DYLB080", "DYLB073", "DYLB072", "DYLB071", "DYLB065", "DYLP202", "DYLP204", "DYLP203", "DYLP021", "DYLP020", "DYLP034", "DYLP087", "DYLP086", "DYLP083", "DYLP082", "DYLP081", "DYLP095", "DYLP090", "DYLP089", "DYLP104", "DYLP098", "DYLP066", "DYLP065", "DYLP064", "DYLP080", "DYLP073", "DYLP072", "DYLP071", "DYLP070", "DYLP174", "DYLP170", "DYLP084", "DYLP028", "DYLP085", "DYLP005", "DYLP099", "DYLP047", "DYLP029"),
                     loc_type = c("P", "B"),
                     loc_validity = c("VLD", "ENT"),
                     filterdepth_range = c(0, 30))
# locaties %>% collect() %>% knitr::kable()
```

```{r tijdreeks}
tijdreeks <-
  locaties %>% 
  rename(mvTAW = soilsurf_ost) %>% 
  inner_join(tbl(watina, "FactPeilMeting"), by = c("loc_wid" = "MeetpuntWID")) %>% 
  inner_join(tbl(watina, "DimTijd"), by = c("TijdWID" = "DatumWID")) %>% 
  dplyr::collect()
```

# Tijdreeksen per raai

## Raai 1

### Kaart

```{r kaart_raai_1}
komgr_neerijse <- locaties %>%
  collect() %>% 
  st_as_sf(coords = c("x", "y"), crs = 31370) %>% 
  st_transform(crs = 4326)

leaflet(data = komgr_neerijse) %>%
  addTiles() %>% 
  # addProviderTiles("OpenTopoMap") %>% 
  addCircleMarkers(label = komgr_neerijse$loc_code, fill = FALSE, weight = 3, color = "red",
             labelOptions = labelOptions(noHide = TRUE, textOnly = FALSE,
                                         direction = "right", opacity = 0.75)) %>% 
  addMiniMap(toggleDisplay = TRUE,zoomLevelOffset = -5)
```

### Tijdreeks

```{r tijdreeks_raai_1, message=FALSE, warning=FALSE}
plot_tijdreeks_trans_mom_1 <- ggplot(tijdreeks %>% 
                           filter(transect_nr == 1)) +
  geom_line(aes(x = date(Datum),
                y = mMaaiveld,
                colour = paste0(loc_code, " (", round(mvTAW,2), " mTAW)"))) +
  ## non-clipping zoom
  # coord_cartesian(ylim = c(-1, 0.1),
  #                 xlim = c(ymd("2018-01-01"), ymd("2021-01-01"))
  #                 ) +
  scale_x_date(date_breaks = "year", date_labels = "%Y") +
  ## clipping zoom
  xlim(ymd("2017-01-01"), ymd("2020-01-01")) +
  # ylim(-1, 0.1) +
  geom_hline(yintercept = 0, colour = "black", size = 1, linetype = "dotted") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_line(linetype = "dashed")) +
  labs(x = "Datum", y = "m-mv", colour = NULL)
  
plot_tijdreeks_trans_mom_1
```

