---
title: "Dataset validatie overstromingen - Mombeek"
author: "Dries Adriaens"
date: "26-10-2020"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(watina)
library(ggplot2)
library(lubridate)
library(dplyr)
library(stringr)
library(tidyr)
library(sf)
library(leaflet)
```

```{r connection}
watina <- connect_watina()
```

# Meetpunten

We vragen al de meetpunten met peilbuis (piëzometer) in de vallei van de Mombeek op met behulp van het R-package `Watina`.

```{r meetpunten}
locaties <- get_locs(watina,
                     area_codes = "MOM",
                     loc_type = c("P"),
                     loc_validity = c("VLD", "ENT"),
                     filterdepth_range = c(0, 30))
locaties %>% collect() %>% knitr::kable()
```

# Raaien

```{r raaien}
trans_mom_1 <- c("MOMP005", "MOMP006", "MOMP007", "MOMP008", "MOMP009")
trans_mom_2 <- c("MOMP001", "MOMP003", "MOMP004", "MOMP010", "MOMP002",
                 "MOMP011", "MOMP029", "MOMP012", "MOMP013","MOMS001",
                 "MOMS009", "MOMP014",
                 "MOMP015", "MOMP016", "MOMS008")
trans_mom_3 <- c("MOMP027", "MOMS011", "MOMP026", "MOMP025", "MOMP024",
                 "MOMP023", "MOMS007", "MOMS010", "MOMP017", "MOMP018",
                 "MOMP019", "MOMP020", "MOMP021", "MOMP022")
trans_mom_4 <- c("MOMP028")

locs <- locaties %>% collect()
transects <- data.frame(loc_code = locs$loc_code,
                        transect_nr = 0, stringsAsFactors = FALSE) %>% 
  mutate(transect_nr = ifelse(loc_code %in% trans_mom_1, 1,
                              ifelse(loc_code %in% trans_mom_2, 2,
                                     ifelse(loc_code %in% trans_mom_3, 3,
                                            ifelse(loc_code %in% trans_mom_4, 4,
                                                   transect_nr)))))
transects %>% knitr::kable()

locs <- locaties %>% collect() %>% 
  left_join(transects, by = "loc_code")
```

```{r tijdreeks}
tijdreeks <-
  locaties %>% 
  rename(mvTAW = soilsurf_ost) %>% 
  inner_join(tbl(watina, "FactPeilMeting"), by = c("loc_wid" = "MeetpuntWID")) %>% 
  inner_join(tbl(watina, "DimTijd"), by = c("TijdWID" = "DatumWID")) %>% 
  dplyr::collect()

tijdreeks <- tijdreeks %>% 
  left_join(transects, by = "loc_code")
```

# Tijdreeksen per raai

## Raai 1

### Kaart

```{r kaart_raai_1}
locs_transect1 <- locs %>% 
  filter(transect_nr == 1) %>% 
  st_as_sf(coords = c("x", "y"), crs = 31370) %>% 
  st_transform(crs = 4326)

leaflet(data = locs_transect1) %>%
  addTiles() %>% 
  # addProviderTiles("OpenTopoMap") %>% 
  addCircleMarkers(label = locs_transect1$loc_code, fill = FALSE, weight = 3, color = "red",
             labelOptions = labelOptions(noHide = TRUE, textOnly = FALSE,
                                         direction = "right", opacity = 0.75)) %>% 
  addMiniMap(toggleDisplay = TRUE,zoomLevelOffset = -5)
```

### Tijdreeks

```{r tijdreeks_raai_1, message=FALSE, warning=FALSE}
plot_tijdreeks_trans_mom_1 <- ggplot(tijdreeks %>% 
                           filter(transect_nr == 1)) +
  geom_line(aes(x = date(Datum),
                y = mMaaiveld,
                colour = paste0(loc_code, " (", round(mvTAW,2), " mTAW)"))) +
  ## non-clipping zoom
  # coord_cartesian(ylim = c(-1, 0.1),
  #                 xlim = c(ymd("2018-01-01"), ymd("2021-01-01"))
  #                 ) +
  scale_x_date(date_breaks = "year", date_labels = "%Y") +
  ## clipping zoom
  xlim(ymd("2017-01-01"), ymd("2020-01-01")) +
  # ylim(-1, 0.1) +
  geom_hline(yintercept = 0, colour = "black", size = 1, linetype = "dotted") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_line(linetype = "dashed")) +
  labs(x = "Datum", y = "m-mv", colour = NULL)
  
plot_tijdreeks_trans_mom_1
```

## Raai 2

### Kaart

```{r kaart_raai_2}
locs_transect2 <- locs %>% 
  filter(transect_nr == 2) %>% 
  st_as_sf(coords = c("x", "y"), crs = 31370) %>% 
  st_transform(crs = 4326)

leaflet(data = locs_transect2) %>%
  addTiles() %>% 
  # addProviderTiles("OpenTopoMap") %>% 
  addCircleMarkers(label = locs_transect2$loc_code, fill = FALSE, weight = 3, color = "red",
             labelOptions = labelOptions(noHide = TRUE, textOnly = FALSE,
                                         direction = "right", opacity = 0.75)) %>% 
  addMiniMap(toggleDisplay = TRUE,zoomLevelOffset = -5)
```

### Tijdreeks

```{r tijdreeks_raai_2, message=FALSE, warning=FALSE}
plot_tijdreeks_trans_mom_2 <- ggplot(tijdreeks %>% 
                           filter(transect_nr == 2)) +
  geom_line(aes(x = date(Datum),
                y = mMaaiveld,
                colour = paste0(loc_code, " (", round(mvTAW,2), " mTAW)"))) +
  ## non-clipping zoom
  # coord_cartesian(ylim = c(-1, 0.1),
  #                 xlim = c(ymd("2018-01-01"), ymd("2021-01-01"))
  #                 ) +
  scale_x_date(date_breaks = "year", date_labels = "%Y") +
  ## clipping zoom
  xlim(ymd("2017-01-01"), ymd("2020-01-01")) +
  # ylim(-1, 0.1) +
  geom_hline(yintercept = 0, colour = "black", size = 1, linetype = "dotted") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_line(linetype = "dashed")) +
  labs(x = "Datum", y = "m-mv", colour = NULL)
  
plot_tijdreeks_trans_mom_2
```

## Raai 3

### Kaart

```{r kaart_raai_3}
locs_transect3 <- locs %>% 
  filter(transect_nr == 3) %>% 
  st_as_sf(coords = c("x", "y"), crs = 31370) %>% 
  st_transform(crs = 4326)

leaflet(data = locs_transect3) %>%
  addTiles() %>% 
  # addProviderTiles("OpenTopoMap") %>% 
  addCircleMarkers(label = locs_transect3$loc_code, fill = FALSE, weight = 3, color = "red",
             labelOptions = labelOptions(noHide = TRUE, textOnly = FALSE,
                                         direction = "right", opacity = 0.75)) %>% 
  addMiniMap(toggleDisplay = TRUE,zoomLevelOffset = -5)
```

### Tijdreeks

```{r tijdreeks_raai_3, message=FALSE, warning=FALSE}
plot_tijdreeks_trans_mom_3 <- ggplot(tijdreeks %>% 
                           filter(transect_nr == 3)) +
  geom_line(aes(x = date(Datum),
                y = mMaaiveld,
                colour = paste0(loc_code, " (", round(mvTAW,2), " mTAW)"))) +
  ## non-clipping zoom
  # coord_cartesian(ylim = c(-1, 0.1),
  #                 xlim = c(ymd("2018-01-01"), ymd("2021-01-01"))
  #                 ) +
  scale_x_date(date_breaks = "year", date_labels = "%Y") +
  ## clipping zoom
  xlim(ymd("2017-01-01"), ymd("2020-01-01")) +
  # ylim(-1, 0.1) +
  geom_hline(yintercept = 0, colour = "black", size = 1, linetype = "dotted") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_line(linetype = "dashed")) +
  labs(x = "Datum", y = "m-mv", colour = NULL)
  
plot_tijdreeks_trans_mom_3
```

## Raai 4

### Kaart

```{r kaart_raai_4}
locs_transect4 <- locs %>% 
  filter(transect_nr == 4) %>% 
  st_as_sf(coords = c("x", "y"), crs = 31370) %>% 
  st_transform(crs = 4326)

leaflet(data = locs_transect4) %>%
  addTiles() %>% 
  # addProviderTiles("OpenTopoMap") %>% 
  addCircleMarkers(label = locs_transect4$loc_code, fill = FALSE, weight = 3, color = "red",
             labelOptions = labelOptions(noHide = TRUE, textOnly = FALSE,
                                         direction = "right", opacity = 0.75)) %>% 
  addMiniMap(toggleDisplay = TRUE,zoomLevelOffset = -5)
```

### Tijdreeks

```{r tijdreeks_raai_4, message=FALSE, warning=FALSE}
plot_tijdreeks_trans_mom_4 <- ggplot(tijdreeks %>% 
                           filter(transect_nr == 4)) +
  geom_line(aes(x = date(Datum),
                y = mMaaiveld,
                colour = paste0(loc_code, " (", round(mvTAW,2), " mTAW)"))) +
  ## non-clipping zoom
  # coord_cartesian(ylim = c(-1, 0.1),
  #                 xlim = c(ymd("2018-01-01"), ymd("2021-01-01"))
  #                 ) +
  scale_x_date(date_breaks = "year", date_labels = "%Y") +
  ## clipping zoom
  xlim(ymd("2017-01-01"), ymd("2020-01-01")) +
  # ylim(-1, 0.1) +
  geom_hline(yintercept = 0, colour = "black", size = 1, linetype = "dotted") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        panel.grid.minor.x = element_line(linetype = "dashed")) +
  labs(x = "Datum", y = "m-mv", colour = NULL)
  
plot_tijdreeks_trans_mom_4
```

